# -*- coding: utf-8 -*-
"""etl_clientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9NoWPUbNX4xxWXmnqiNZdOU-z6E5tzC
"""

!pip install sqlalchemy psycopg2-binary

"""RAW CLIENTES

https://raw.githubusercontent.com/MendezBy02/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv
"""

from sqlalchemy import create_engine

import pandas as pd

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

"""Mostrar tabla

"""

url="https://raw.githubusercontent.com/eduardorivas2517502022/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv"
df = pd.read_csv(url)
df.head()

"""#Limpieza de datos"""

clientes = df.copy()

clientes.columns = clientes.columns.str.strip().str.lower()

for col in clientes.select_dtypes(include='object').columns:
  clientes[col]=clientes[col].astype(str).str.strip()

clientes = clientes.replace(r'^\s*$', pd.NA, regex=True)
clientes['email'] = clientes['email'].str.lower()

clientes['fecha_nacimiento'] = pd.to_datetime(clientes['fecha_nacimiento'], errors='coerce')

clientes = clientes.drop_duplicates()

"""#Separar datos validos y rechazados"""

validos = clientes[
    clientes['nombre'].notna()&
    clientes['email'].notna()
].copy()

rechazados = clientes[
    clientes['nombre'].isna() |
    clientes['email'].isna()
].copy()

"""Motivo de rechazo"""

clientes = df.copy()

clientes.columns = clientes.columns.str.strip().str.lower()

for col in clientes.select_dtypes(include='object').columns:
  clientes[col]=clientes[col].astype(str).str.strip()

clientes = clientes.replace(r'^\s*$', pd.NA, regex=True)
clientes['email'] = clientes['email'].str.lower()

clientes['fecha_nacimiento'] = pd.to_datetime(clientes['fecha_nacimiento'], errors='coerce')

clientes = clientes.drop_duplicates()


validos = clientes[
    clientes['nombre'].notna()&
    clientes['email'].notna()
].copy()

rechazados = clientes[
    clientes['nombre'].isna() |
    clientes['email'].isna()
].copy()

def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['email']):
        motivos.append("email_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

"""Exportar Archivos"""

validos.to_csv("clientes_curated.csv", index = False)

rechazados.to_csv("clientes_rejects.csv", index=False)

"""Conectar con PostgreSQL Cloud"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine(
"postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
)

test = pd.read_sql("SELECT 1", engine)

print(test)

"""Cargar datos en PostgreSQL"""

validos.to_sql(
    'clientes_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'clientes_rejects',
    engine,
    if_exists='append',
    index=False
)

"""Validar la Carga"""

pd.read_sql(
"SELECT * FROM clientes_curated LIMIT 10",
engine
)