# -*- coding: utf-8 -*-
"""etl_aseguradoras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANV2O-IUdRyAkGJAKFFJ5xm8xHkJlcdX

Importar Librerias
"""

import pandas as pd
import numpy as np

"""Conexion a PostgreSQL"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
engine = create_engine(database_url)

# Probar conexión
with engine.connect() as conn:
    print("Conectado correctamente")

"""Cargar Dataset"""

#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/eduardorivas2517502022/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

aseguradoras = pd.read_csv(url)

"""Exploración de datos"""

aseguradoras.head()

aseguradoras.info()

aseguradoras.isnull().sum()

aseguradoras.duplicated().sum()

"""Funciones reutilizables"""

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

"""Aplicar Limpieza"""

aseguradoras = normalizar_columnas(aseguradoras)
aseguradoras = limpiar_texto(aseguradoras)
aseguradoras = aseguradoras.drop_duplicates()

"""Funciones especificas"""

#Normalización de pais

map_pais = {
    "elsalvador": "El Salvador",
    "el salvador": "El Salvador",
    "costa rica": "Costa Rica"
}

aseguradoras["pais"] = (
    aseguradoras["pais"]
    .str.lower()
    .replace(map_pais)
)

#Estandarizar raiting

map_rating = {
    "alto": "Alto",
    "a": "Alto",
    "medio": "Medio",
    "m": "Medio",
    "bajo": "Bajo",
    "b": "Bajo"
}

aseguradoras["rating_riesgo"] = (
    aseguradoras["rating_riesgo"]
    .astype(str)
    .str.strip()
    .str.lower()
    .replace(map_rating)
    )

aseguradoras["pais"] = aseguradoras["pais"].fillna("No especificado")


valores_validos = ["Alto", "Medio", "Bajo"]

aseguradoras.loc[
    ~aseguradoras["rating_riesgo"].isin(valores_validos),
    "rating_riesgo"] = np.nan
aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].fillna("No especificado")
aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].str.title()

aseguradoras.head()

aseguradoras["rating_riesgo"].value_counts(dropna=False)

"""Separar Validos y rechazados"""

#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. El id debe ser not null
#2 el nombre debe ser not null

validos = aseguradoras[
    aseguradoras["id_aseguradora"].notna() &
    aseguradoras["nombre"].notna()
].copy()

rechazados = aseguradoras [
    ~aseguradoras["id_aseguradora"].isna() |
    ~aseguradoras["nombre"].isna()
]

"""Motivo del rechazo"""

def motivo(row):

  motivos = []

  if pd.isna(row["id_aseguradora"]):
    motivos.append("Id_no_valido")

    if pd.isna(row["nombre"]):
      motivos.append("Nombre_no_valido")

    return ",".join(motivos)

    rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

"""Exportar Archivos"""

validos.to_csv("aseguradoras_curated.csv", index=False)
rechazados.to_csv("aseguradoras_rejects.csv", index=False)

"""Cargar datos en PostgreSQL"""

validos.to_sql(
    "aseguradoras",
    engine,
    if_exists="append",
    index=False
  )

"""Validar Carga"""

pd.read_sql(
    "Select * From aseguradoras Limit 100",
    engine
)