# -*- coding: utf-8 -*-
"""etl_corredores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqVESfTvXKBlynao7yRMyN1jIfLQ292P

Importar Librerias
"""

import pandas as pd
import numpy as np

"""Conexion a PostgreSQL"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
engine = create_engine(database_url)

# Probar conexión
with engine.connect() as conn:
    print("Conectado correctamente")

"""Cargar Dataset"""

#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/eduardorivas2517502022/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv"

corredores = pd.read_csv(url)

"""Exploración de datos"""

corredores.head()

corredores.info()

corredores.isnull().sum()

corredores.duplicated().sum()

"""Funciones reutilizables"""

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

"""Aplicar Limpieza"""

corredores = normalizar_columnas(corredores)
corredores = limpiar_texto(corredores)
corredores = corredores.drop_duplicates()

"""Funciones especificas"""

#Normalización de nivel

map_nivel = {
    "mid": "Mid",
    "MID": "Mid",
    "SENIOR": "Senior",
    "senior": "Senior",
    "JUNIOR": "Junior",
    "junior": "Junior",
    "ELITE":"Elite" ,
    "elite" : "Elite"
}

corredores["nivel"] = (
    corredores["nivel"]
    .astype(str)
    .str.strip()
    .replace(map_nivel)
)

#Convertir a entero datos decimal
corredores["anios_experiencia"] = pd.to_numeric(
    corredores["anios_experiencia"],
    errors="coerce"
)


corredores["anios_experiencia"] = corredores["anios_experiencia"].astype("Int64")

corredores.info()

corredores.head()

"""Separar validos y rechazados"""

#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. Los tipo ID's deben ser not null
#2. No debe haber datos vacios

columnas_obligatorias = [
   "id_corredor",
   "nombre",
   "zona",
   "anios_experiencia"
]

condicion_nulos = corredores[columnas_obligatorias].isna().any(axis=1)

condicion_exp_invalida = (
     (corredores["anios_experiencia"] < 0) |
    (corredores["anios_experiencia"] > 50)
)

condicion_rechazo = condicion_nulos | condicion_exp_invalida

rechazados = corredores.loc[condicion_rechazo].copy()
validos = corredores.loc[~condicion_rechazo].copy()

"""Motivo del rechazo"""

from pandas.core.dtypes.missing import isna
def motivo(row):

  motivos = []

  if pd.isna(row["id_corredor"]):
    motivos.append("ID_no_valido")

  if pd.isna(row["nombre"]):
    motivos.append("Nombre_nulo")

  if pd.isna(row["zona"]):
    motivos.append("Zona_nula")

  if pd.isna(row["anios_experiencia"]):
    motivos.append("anios_experiencia_nulo")

  elif row["anios_experiencia"] > 50:
      motivos.append("Experiencia_fuera_de_rango")

  return ",".join(motivos)

"""Agregar motivo de rechazo"""

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

"""Exportar Archivos"""

validos.to_csv("corredores_curated.csv", index=False)
rechazados.to_csv("corredores_rejects.csv", index=False)

"""Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles
"""

corredores.head()

corredores.dtypes

corredores.isnull().sum()

corredores.value_counts()

validos.to_sql(
    "corredores",
    engine,
    if_exists="append",
    index=False
  )

"""Validar Carga"""

pd.read_sql(
    "Select * From corredores Limit 100",
    engine
)