# -*- coding: utf-8 -*-
"""etl_polizas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_xSPLmp_PAk2yH_uP0uR-WfCPilYpwso

Importar Librerias
"""

import pandas as pd
import numpy as np

"""Conexion a PostgreSQL"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
engine = create_engine(database_url)

# Probar conexión
with engine.connect() as conn:
    print("Conectado correctamente")

"""Cargar Dataset"""

#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/eduardorivas2517502022/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

polizas = pd.read_csv(url)

"""Exploración de datos"""

polizas.head()

polizas.info()

polizas.isnull().sum()

polizas.duplicated().sum()

"""Funciones reutilizables"""

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

"""Aplicar Limpieza"""

polizas = normalizar_columnas(polizas)
polizas = limpiar_texto(polizas)
polizas = polizas.drop_duplicates()

"""Funciones especificas"""

#Convertir fecha a dateTime

polizas["fecha_emision"] = pd.to_datetime(
    polizas["fecha_emision"],
    errors = "coerce",
    format= "mixed"
    )



#Limpiar datos monetarios
polizas["prima"] = (
    polizas["prima"]
    .astype(str)
    .str.replace("","", regex=False)
)



#Convertir a float los datos con decimal
polizas["prima"] = pd.to_numeric(
    polizas["prima"],
    errors = "coerce"
    )

polizas["comision"]= pd.to_numeric(
    polizas["comision"],
    errors = "coerce"
    )

polizas["monto_asegurado"] = pd.to_numeric(
    polizas["monto_asegurado"],
    errors = "coerce"
    )

polizas["fecha_emision"].isnull().sum()

polizas.info()

polizas.head()

#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. Los tipo ID's deben ser not null
#2. las fechas deben ser validas
#3. los campos monetarios no pueden quedar vacios o ser nulos

columnas_obligatorias = [
    "id_poliza",
    "fecha_emision",
    "id_cliente",
    "id_corredor",
    "id_aseguradora",
    "id_tipo_seguro",
    "prima",
    "comision",
    "monto_asegurado"
]

validos = polizas[
    polizas[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = polizas [
    polizas[columnas_obligatorias].isna().any(axis=1)
].copy()

rechazados_negativos= polizas[
    (polizas["prima"] < 0) |
    (polizas["comision"] < 0) |
    (polizas["monto_asegurado"] < 0)
].copy()

"""Motivo del rechazo"""

def motivo(row):

  motivos = []

  if pd.isna(row["id_poliza"]):
    motivos.append("id_poliza es nulo")

  if pd.isna(row["fecha_emision"]):
    motivos.append("Fecha_emision es nulo")

  if pd.isna(row["id_cliente"]):
    motivos.append("id_cliente es nulo")

  if pd.isna(row["id_corredor"]):
    motivos.append("id_corredor")

  if pd.isna(row["id_aseguradora"]):
    motivos.append("id_aseguradora")

  if pd.isna(row["id_tipo_seguro"]):
    motivos.append("id_tipo_seguro")

  if pd.isna(row["prima"]):
    motivos.append("prima_vacia_o_negativa")

  if pd.isna(row["comision"]):
    motivos.append("comision_vacia_o_negativo")

  if pd.isna(row["monto_asegurado"]):
    motivos.append("monto_asegurado_vacio_o_negativo")

"""Exportar Archivos"""

validos.to_csv("polizas_curated.csv", index=False)
rechazados.to_csv("polizas_rejects.csv", index=False)

"""Cargar datos en PostgreSQL"""

validos.to_sql(
    "polizas",
    engine,
    if_exists="append",
    index=False
  )

"""Validar Carga"""

pd.read_sql(
    "Select * From polizas Limit 100",
    engine
)