# -*- coding: utf-8 -*-
"""etl_siniestros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W7rLPJwEonRwAmWWAaGUYCjGpR57Ts3d

Importar Librerias
"""

import pandas as pd
import numpy as np

"""Conexion a PostgreSQL"""

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
engine = create_engine(database_url)

# Probar conexión
with engine.connect() as conn:
    print("Conectado correctamente")

"""Cargar Dataset"""

#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/eduardorivas2517502022/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"
siniestros = pd.read_csv(url)

"""Exploración de datos"""

siniestros.head()

siniestros.info()

siniestros.isnull().sum()

siniestros.duplicated().sum()

"""Funciones reutilizables"""

#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

"""Aplicar Limpieza"""

siniestros = normalizar_columnas(siniestros)
siniestros = limpiar_texto(siniestros)
siniestros = siniestros.drop_duplicates()

"""Funciones especificas"""

#Normalización de estado

map_estado = {
    "RECHAZADO": "Rechazado",
    "rechazado": "Rechazado",
    "ABIERTO": "Abierto",
    "abierto": "Abierto",
    "CERRADO": "Cerrado",
    "cerrado": "Cerrado",
}

siniestros["estado"] = (
    siniestros["estado"]
    .astype(str)
    .str.strip()
    .replace(map_estado)
)

siniestros["monto_siniestro"] = (

   siniestros["monto_siniestro"]
   .astype(str)
   .str.replace(",",".",regex=False)
)

#Convertir decimal
siniestros["monto_siniestro"] = pd.to_numeric(
    siniestros["monto_siniestro"],
    errors="coerce"
)


#Un solo formato para fecha
siniestros["fecha_siniestro"] = (
  siniestros["fecha_siniestro"]
  .astype(str)
  .str.replace("-","/",regex=False)
)

#Convertir a DateTime fecha_siniestro
siniestros["fecha_siniestro"] = pd.to_datetime(
    siniestros["fecha_siniestro"],
    errors="coerce",
    dayfirst=True
)

siniestros.info()

siniestros.head()

"""Separar validos y rechazados"""

#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. Los tipo ID's deben ser not null
#2. no debe haber espacios vcios en monto_siniestro ni en estado

columnas_obligatorias = [
    "id_siniestro",
    "id_poliza",
    "fecha_siniestro",
    "monto_siniestro",
    "estado"
]

condicion_nulos = siniestros[columnas_obligatorias].isna().any(axis=1)

condicion_monto_invalido = siniestros["monto_siniestro"] <= 0

condicion_rechazo = condicion_nulos | condicion_monto_invalido

rechazados = siniestros.loc[condicion_rechazo].copy()
validos = siniestros.loc[~condicion_rechazo].copy()

"""Motivo del rechazo"""

from pandas.core.dtypes.missing import isna
def motivo(row):

  motivos = []

  if pd.isna(row["id_siniestro"]):
    motivos.append("ID_no_valido")

  if pd.isna(row["id_poliza"]):
    motivos.append("ID_no_valido")

  if pd.isna(row["fecha_siniestro"]):
    motivos.append("fecha_nula_o_invalida")

  if pd.isna(row["estado"]):
    motivos.append("estado_no_valido")

  if pd.isna(row["monto_siniestro"]):
    motivos.append("monto_siniestro_no_valido")

  elif row["monto_siniestro"] < 0:
      motivos.append("monto_siniestro_invalido")

  return ",".join(motivos)

"""Agregar motivo de rechazo"""

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

"""Exportar Archivos"""

validos.to_csv("siniestros_curated.csv", index=False)
rechazados.to_csv("siniestros_rejects.csv", index=False)

"""Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles
"""

siniestros.head()

siniestros.dtypes

siniestros.isnull().sum()

siniestros.value_counts()

validos.to_sql(
    "siniestros",
    engine,
    if_exists="append",
    index=False
  )

"""Validar Carga"""

pd.read_sql(
    "Select * From siniestros Limit 100",
    engine
)