# -*- coding: utf-8 -*-
"""etl_tipos_seguro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b37yJz0BHnCP95hyoAXVYOcVEr-MUgOd

Importar Librerias
"""

import pandas as pd
import numpy as np

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
engine = create_engine(database_url)

# Probar conexión
with engine.connect() as conn:
    print("Conectado correctamente")

"""Cargar Dataset"""

url_tipos = "https://raw.githubusercontent.com/eduardorivas2517502022/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"
tipos_seguro = pd.read_csv(url_tipos)
tipos_seguro.head()

"""Exploración de datos"""

tipos_seguro.shape

tipos_seguro.columns

tipos_seguro.info()

tipos_seguro.isnull().sum()

"""Normalizar nombres de columnas (Estandarización de esquemas)"""

tipos_seguro.columns= (
    tipos_seguro.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

"""Limpieza de texto

Reglas:

1.   id_tipo_seguro no puede ser nulo
2.   tipo no puede ser nulo


"""

for col in tipos_seguro.select_dtypes(include="object").columns:
  tipos_seguro[col] = tipos_seguro[col].astype(str).str.strip()
  tipos_seguro[col] = tipos_seguro[col].replace(
      ["nan","None","NULL", "null",""],
      pd.NA
  )

  validos = tipos_seguro[
      tipos_seguro["id_tipo_seguro"].notna() &
      tipos_seguro["tipo"].notna()
  ].copy()

  rechazados = tipos_seguro[
      tipos_seguro["id_tipo_seguro"].isna() |
      tipos_seguro["tipo"].isna()
  ].copy()

"""Motivo de rechazo"""

def motivo(row):
  motivos=[]

  if pd.isna(row['id_tipo_seguro']):
    motivos.append("id_vacio")

  if pd.isna(row['tipo']):
    motivos.append("tipo_vacio")

    return ",".join(motivos)

"""Aplicar funcion"""

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

"""Eliminar Duplicados"""

tipos_seguro = tipos_seguro.drop_duplicates()

"""Transformación de texto"""

tipos_seguro["tipo"] = tipos_seguro["tipo"].str.title()
tipos_seguro["categoria"] = tipos_seguro["categoria"].str.title()

"""Reemplazar categoria vacia"""

tipos_seguro["categoria"] = tipos_seguro["categoria"].fillna("No especificado")

"""Limpiar Números"""

tipos_seguro["riesgo_base"] = tipos_seguro["riesgo_base"].replace("-", np.nan)

tipos_seguro["riesgo_base"] = pd.to_numeric(
    tipos_seguro["riesgo_base"], errors="coerce"
)

"""Exportación de dataset limpio"""

tipos_seguro.to_csv(
    "tipos_seguro_curated.csv",
    index = False
)

"""Exportar dataset de rechazos"""

rechazados.to_csv("tipos_seguro_rejects.csv", index=False)

"""Conectar con PostgreSQL"""

#Instalamos librerias
!pip install sqlalchemy psycopg2-binary

"""Conexión"""

from sqlalchemy import create_engine

database_url = "postgresql://etl_seguros_00iw_user:FZBRc2UIzW86Fj6UIVV9CV4CdJKc8hIi@dpg-d6qu533uibrs739hde4g-a.oregon-postgres.render.com/etl_seguros_00iw"
engine = create_engine(database_url)

"""Cargar datos a PostgreSQL"""

tipos_seguro.to_sql(
    "tipos_seguro",
    engine,
    if_exists="append",
    index=False
)

"""Validar que se cargó"""

pd.read_sql(
    "Select * from tipos_seguro LIMIT 10",
    engine
)